language: cpp
notifications:
  email: false
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install valgrind
before_script:
  - mkdir install_tmp
script:
  - ./script/travis-cmake .
  - make
  - DESTDIR=install_tmp make install
  - valgrind --leak-check=full --error-exitcode=1 ./sample/sample
  - ./script/travis-cmake -DTEST=true .
  - make
  - make test
